// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: message.proto
// Protobuf C++ Version: 5.29.5

#include "message.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace nt_msg {

inline constexpr Element_SourceMsgTextElem::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : textelemcontent_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        unknown_45001_{::int64_t{0}},
        replyabselemtype_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Element_SourceMsgTextElem::Element_SourceMsgTextElem(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct Element_SourceMsgTextElemDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Element_SourceMsgTextElemDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Element_SourceMsgTextElemDefaultTypeInternal() {}
  union {
    Element_SourceMsgTextElem _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Element_SourceMsgTextElemDefaultTypeInternal _Element_SourceMsgTextElem_default_instance_;

inline constexpr Element::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        sourcemsgtextelems_{},
        senderuidstr_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        textstr_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        filename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        md5_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        fileuuid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        imageurl198_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        imageurl720_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        originimageurl_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        picpath_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        elementid_{::int64_t{0}},
        elementtype_{0},
        attype_{0},
        filesize_{0},
        picwidth_{0},
        picheight_{0},
        unknown_45413_{0},
        unknown_45414_{0},
        pictype_{0},
        unknown_45418_{0},
        unknown_45805_{0},
        unknown_45806_{::int64_t{0}},
        unknown_45807_{0},
        unknown_45829_{0},
        replaymsgseq_{0},
        senderuid_{0},
        replymsgtime_{0},
        unknown_47411_{0},
        unknown_47416_{::int64_t{0}},
        unknown_47422_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR Element::Element(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ElementDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ElementDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ElementDefaultTypeInternal() {}
  union {
    Element _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ElementDefaultTypeInternal _Element_default_instance_;

inline constexpr Elements::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : elem_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Elements::Elements(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ElementsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ElementsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ElementsDefaultTypeInternal() {}
  union {
    Elements _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ElementsDefaultTypeInternal _Elements_default_instance_;
}  // namespace nt_msg
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_message_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_message_2eproto = nullptr;
const ::uint32_t
    TableStruct_message_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element_SourceMsgTextElem, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element_SourceMsgTextElem, _impl_.unknown_45001_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element_SourceMsgTextElem, _impl_.replyabselemtype_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element_SourceMsgTextElem, _impl_.textelemcontent_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _impl_.elementid_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _impl_.elementtype_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _impl_.textstr_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _impl_.attype_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _impl_.filename_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _impl_.filesize_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _impl_.md5_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _impl_.picwidth_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _impl_.picheight_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _impl_.unknown_45413_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _impl_.unknown_45414_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _impl_.pictype_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _impl_.unknown_45418_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _impl_.fileuuid_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _impl_.imageurl198_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _impl_.imageurl720_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _impl_.originimageurl_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _impl_.unknown_45805_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _impl_.unknown_45806_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _impl_.unknown_45807_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _impl_.picpath_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _impl_.unknown_45829_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _impl_.senderuidstr_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _impl_.replaymsgseq_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _impl_.senderuid_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _impl_.replymsgtime_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _impl_.unknown_47411_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _impl_.unknown_47416_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _impl_.unknown_47422_),
        PROTOBUF_FIELD_OFFSET(::nt_msg::Element, _impl_.sourcemsgtextelems_),
        ~0u,
        ~0u,
        1,
        9,
        2,
        10,
        3,
        11,
        12,
        13,
        14,
        15,
        16,
        4,
        5,
        6,
        7,
        17,
        18,
        19,
        8,
        20,
        0,
        21,
        22,
        23,
        24,
        25,
        26,
        ~0u,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::nt_msg::Elements, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::nt_msg::Elements, _impl_.elem_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::nt_msg::Element_SourceMsgTextElem)},
        {11, 49, -1, sizeof(::nt_msg::Element)},
        {79, -1, -1, sizeof(::nt_msg::Elements)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::nt_msg::_Element_SourceMsgTextElem_default_instance_._instance,
    &::nt_msg::_Element_default_instance_._instance,
    &::nt_msg::_Elements_default_instance_._instance,
};
const char descriptor_table_protodef_message_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\rmessage.proto\022\006nt_msg\"\245\013\n\007Element\022\023\n\te"
    "lementId\030\311\337\002 \001(\003\022\025\n\013elementType\030\312\337\002 \001(\005\022"
    "\026\n\007textStr\030\255\340\002 \001(\tH\000\210\001\001\022\025\n\006atType\030\256\340\002 \001("
    "\005H\001\210\001\001\022\027\n\010fileName\030\332\342\002 \001(\tH\002\210\001\001\022\027\n\010fileS"
    "ize\030\335\342\002 \001(\005H\003\210\001\001\022\022\n\003md5\030\336\342\002 \001(\014H\004\210\001\001\022\027\n\010"
    "picWidth\030\343\342\002 \001(\005H\005\210\001\001\022\030\n\tpicHeight\030\344\342\002 \001"
    "(\005H\006\210\001\001\022\034\n\runknown_45413\030\345\342\002 \001(\005H\007\210\001\001\022\034\n"
    "\runknown_45414\030\346\342\002 \001(\005H\010\210\001\001\022\026\n\007picType\030\350"
    "\342\002 \001(\005H\t\210\001\001\022\034\n\runknown_45418\030\352\342\002 \001(\005H\n\210\001"
    "\001\022\027\n\010fileUuid\030\277\343\002 \001(\tH\013\210\001\001\022\032\n\013imageUrl19"
    "8\030\352\345\002 \001(\tH\014\210\001\001\022\032\n\013imageUrl720\030\353\345\002 \001(\tH\r\210"
    "\001\001\022\035\n\016originImageUrl\030\354\345\002 \001(\tH\016\210\001\001\022\034\n\runk"
    "nown_45805\030\355\345\002 \001(\005H\017\210\001\001\022\034\n\runknown_45806"
    "\030\356\345\002 \001(\003H\020\210\001\001\022\034\n\runknown_45807\030\357\345\002 \001(\005H\021"
    "\210\001\001\022\026\n\007picPath\030\364\345\002 \001(\tH\022\210\001\001\022\034\n\runknown_4"
    "5829\030\205\346\002 \001(\005H\023\210\001\001\022\033\n\014senderUidStr\030\324\270\002 \001("
    "\tH\024\210\001\001\022\033\n\014replayMsgSeq\030\252\362\002 \001(\005H\025\210\001\001\022\030\n\ts"
    "enderUid\030\253\362\002 \001(\005H\026\210\001\001\022\033\n\014replyMsgTime\030\254\362"
    "\002 \001(\005H\027\210\001\001\022\034\n\runknown_47411\030\263\362\002 \001(\005H\030\210\001\001"
    "\022\034\n\runknown_47416\030\270\362\002 \001(\003H\031\210\001\001\022\034\n\runknow"
    "n_47422\030\276\362\002 \001(\003H\032\210\001\001\022\?\n\022sourceMsgTextEle"
    "ms\030\277\362\002 \003(\0132!.nt_msg.Element.SourceMsgTex"
    "tElem\032c\n\021SourceMsgTextElem\022\027\n\runknown_45"
    "001\030\311\337\002 \001(\003\022\032\n\020replyAbsElemType\030\312\337\002 \001(\005\022"
    "\031\n\017textElemContent\030\255\340\002 \001(\t\"B\n\007MsgType\022\022\n"
    "\016MSG_TYPE_ERROR\020\000\022\021\n\rMSG_TYPE_TEXT\020\001\022\020\n\014"
    "MSG_TYPE_PIC\020\002B\n\n\010_textStrB\t\n\007_atTypeB\013\n"
    "\t_fileNameB\013\n\t_fileSizeB\006\n\004_md5B\013\n\t_picW"
    "idthB\014\n\n_picHeightB\020\n\016_unknown_45413B\020\n\016"
    "_unknown_45414B\n\n\010_picTypeB\020\n\016_unknown_4"
    "5418B\013\n\t_fileUuidB\016\n\014_imageUrl198B\016\n\014_im"
    "ageUrl720B\021\n\017_originImageUrlB\020\n\016_unknown"
    "_45805B\020\n\016_unknown_45806B\020\n\016_unknown_458"
    "07B\n\n\010_picPathB\020\n\016_unknown_45829B\017\n\r_sen"
    "derUidStrB\017\n\r_replayMsgSeqB\014\n\n_senderUid"
    "B\017\n\r_replyMsgTimeB\020\n\016_unknown_47411B\020\n\016_"
    "unknown_47416B\020\n\016_unknown_47422\"+\n\010Eleme"
    "nts\022\037\n\004elem\030\340\276\002 \003(\0132\017.nt_msg.Elementb\006pr"
    "oto3"
};
static ::absl::once_flag descriptor_table_message_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_message_2eproto = {
    false,
    false,
    1524,
    descriptor_table_protodef_message_2eproto,
    "message.proto",
    &descriptor_table_message_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_message_2eproto::offsets,
    file_level_enum_descriptors_message_2eproto,
    file_level_service_descriptors_message_2eproto,
};
namespace nt_msg {
const ::google::protobuf::EnumDescriptor* Element_MsgType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_message_2eproto);
  return file_level_enum_descriptors_message_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Element_MsgType_internal_data_[] = {
    196608u, 0u, };
bool Element_MsgType_IsValid(int value) {
  return 0 <= value && value <= 2;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr Element_MsgType Element::MSG_TYPE_ERROR;
constexpr Element_MsgType Element::MSG_TYPE_TEXT;
constexpr Element_MsgType Element::MSG_TYPE_PIC;
constexpr Element_MsgType Element::MsgType_MIN;
constexpr Element_MsgType Element::MsgType_MAX;
constexpr int Element::MsgType_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class Element_SourceMsgTextElem::_Internal {
 public:
};

Element_SourceMsgTextElem::Element_SourceMsgTextElem(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:nt_msg.Element.SourceMsgTextElem)
}
inline PROTOBUF_NDEBUG_INLINE Element_SourceMsgTextElem::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::nt_msg::Element_SourceMsgTextElem& from_msg)
      : textelemcontent_(arena, from.textelemcontent_),
        _cached_size_{0} {}

Element_SourceMsgTextElem::Element_SourceMsgTextElem(
    ::google::protobuf::Arena* arena,
    const Element_SourceMsgTextElem& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Element_SourceMsgTextElem* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, unknown_45001_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, unknown_45001_),
           offsetof(Impl_, replyabselemtype_) -
               offsetof(Impl_, unknown_45001_) +
               sizeof(Impl_::replyabselemtype_));

  // @@protoc_insertion_point(copy_constructor:nt_msg.Element.SourceMsgTextElem)
}
inline PROTOBUF_NDEBUG_INLINE Element_SourceMsgTextElem::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : textelemcontent_(arena),
        _cached_size_{0} {}

inline void Element_SourceMsgTextElem::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, unknown_45001_),
           0,
           offsetof(Impl_, replyabselemtype_) -
               offsetof(Impl_, unknown_45001_) +
               sizeof(Impl_::replyabselemtype_));
}
Element_SourceMsgTextElem::~Element_SourceMsgTextElem() {
  // @@protoc_insertion_point(destructor:nt_msg.Element.SourceMsgTextElem)
  SharedDtor(*this);
}
inline void Element_SourceMsgTextElem::SharedDtor(MessageLite& self) {
  Element_SourceMsgTextElem& this_ = static_cast<Element_SourceMsgTextElem&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.textelemcontent_.Destroy();
  this_._impl_.~Impl_();
}

inline void* Element_SourceMsgTextElem::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Element_SourceMsgTextElem(arena);
}
constexpr auto Element_SourceMsgTextElem::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Element_SourceMsgTextElem),
                                            alignof(Element_SourceMsgTextElem));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Element_SourceMsgTextElem::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Element_SourceMsgTextElem_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Element_SourceMsgTextElem::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Element_SourceMsgTextElem>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Element_SourceMsgTextElem::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Element_SourceMsgTextElem>(), &Element_SourceMsgTextElem::ByteSizeLong,
            &Element_SourceMsgTextElem::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Element_SourceMsgTextElem, _impl_._cached_size_),
        false,
    },
    &Element_SourceMsgTextElem::kDescriptorMethods,
    &descriptor_table_message_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Element_SourceMsgTextElem::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 3, 0, 56, 12> Element_SourceMsgTextElem::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    45101, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nt_msg::Element_SourceMsgTextElem>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    45001, 0, 1,
    65532, 0,45101, 0, 1,
     65534, 2,
    65535, 65535
  }}, {{
    // int64 unknown_45001 = 45001;
    {PROTOBUF_FIELD_OFFSET(Element_SourceMsgTextElem, _impl_.unknown_45001_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // int32 replyAbsElemType = 45002;
    {PROTOBUF_FIELD_OFFSET(Element_SourceMsgTextElem, _impl_.replyabselemtype_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string textElemContent = 45101;
    {PROTOBUF_FIELD_OFFSET(Element_SourceMsgTextElem, _impl_.textelemcontent_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\40\0\0\17\0\0\0\0"
    "nt_msg.Element.SourceMsgTextElem"
    "textElemContent"
  }},
};

PROTOBUF_NOINLINE void Element_SourceMsgTextElem::Clear() {
// @@protoc_insertion_point(message_clear_start:nt_msg.Element.SourceMsgTextElem)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.textelemcontent_.ClearToEmpty();
  ::memset(&_impl_.unknown_45001_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.replyabselemtype_) -
      reinterpret_cast<char*>(&_impl_.unknown_45001_)) + sizeof(_impl_.replyabselemtype_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Element_SourceMsgTextElem::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Element_SourceMsgTextElem& this_ = static_cast<const Element_SourceMsgTextElem&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Element_SourceMsgTextElem::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Element_SourceMsgTextElem& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:nt_msg.Element.SourceMsgTextElem)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int64 unknown_45001 = 45001;
          if (this_._internal_unknown_45001() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteInt64ToArray(
                45001, this_._internal_unknown_45001(), target);
          }

          // int32 replyAbsElemType = 45002;
          if (this_._internal_replyabselemtype() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteInt32ToArray(
                45002, this_._internal_replyabselemtype(), target);
          }

          // string textElemContent = 45101;
          if (!this_._internal_textelemcontent().empty()) {
            const std::string& _s = this_._internal_textelemcontent();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nt_msg.Element.SourceMsgTextElem.textElemContent");
            target = stream->WriteStringMaybeAliased(45101, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:nt_msg.Element.SourceMsgTextElem)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Element_SourceMsgTextElem::ByteSizeLong(const MessageLite& base) {
          const Element_SourceMsgTextElem& this_ = static_cast<const Element_SourceMsgTextElem&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Element_SourceMsgTextElem::ByteSizeLong() const {
          const Element_SourceMsgTextElem& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:nt_msg.Element.SourceMsgTextElem)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string textElemContent = 45101;
            if (!this_._internal_textelemcontent().empty()) {
              total_size += 3 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_textelemcontent());
            }
            // int64 unknown_45001 = 45001;
            if (this_._internal_unknown_45001() != 0) {
              total_size += 3 + ::_pbi::WireFormatLite::Int64Size(
                                              this_._internal_unknown_45001());
            }
            // int32 replyAbsElemType = 45002;
            if (this_._internal_replyabselemtype() != 0) {
              total_size += 3 + ::_pbi::WireFormatLite::Int32Size(
                                              this_._internal_replyabselemtype());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Element_SourceMsgTextElem::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Element_SourceMsgTextElem*>(&to_msg);
  auto& from = static_cast<const Element_SourceMsgTextElem&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:nt_msg.Element.SourceMsgTextElem)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_textelemcontent().empty()) {
    _this->_internal_set_textelemcontent(from._internal_textelemcontent());
  }
  if (from._internal_unknown_45001() != 0) {
    _this->_impl_.unknown_45001_ = from._impl_.unknown_45001_;
  }
  if (from._internal_replyabselemtype() != 0) {
    _this->_impl_.replyabselemtype_ = from._impl_.replyabselemtype_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Element_SourceMsgTextElem::CopyFrom(const Element_SourceMsgTextElem& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nt_msg.Element.SourceMsgTextElem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Element_SourceMsgTextElem::InternalSwap(Element_SourceMsgTextElem* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.textelemcontent_, &other->_impl_.textelemcontent_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Element_SourceMsgTextElem, _impl_.replyabselemtype_)
      + sizeof(Element_SourceMsgTextElem::_impl_.replyabselemtype_)
      - PROTOBUF_FIELD_OFFSET(Element_SourceMsgTextElem, _impl_.unknown_45001_)>(
          reinterpret_cast<char*>(&_impl_.unknown_45001_),
          reinterpret_cast<char*>(&other->_impl_.unknown_45001_));
}

::google::protobuf::Metadata Element_SourceMsgTextElem::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Element::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Element>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Element, _impl_._has_bits_);
};

Element::Element(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:nt_msg.Element)
}
inline PROTOBUF_NDEBUG_INLINE Element::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::nt_msg::Element& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        sourcemsgtextelems_{visibility, arena, from.sourcemsgtextelems_},
        senderuidstr_(arena, from.senderuidstr_),
        textstr_(arena, from.textstr_),
        filename_(arena, from.filename_),
        md5_(arena, from.md5_),
        fileuuid_(arena, from.fileuuid_),
        imageurl198_(arena, from.imageurl198_),
        imageurl720_(arena, from.imageurl720_),
        originimageurl_(arena, from.originimageurl_),
        picpath_(arena, from.picpath_) {}

Element::Element(
    ::google::protobuf::Arena* arena,
    const Element& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Element* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, elementid_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, elementid_),
           offsetof(Impl_, unknown_47422_) -
               offsetof(Impl_, elementid_) +
               sizeof(Impl_::unknown_47422_));

  // @@protoc_insertion_point(copy_constructor:nt_msg.Element)
}
inline PROTOBUF_NDEBUG_INLINE Element::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        sourcemsgtextelems_{visibility, arena},
        senderuidstr_(arena),
        textstr_(arena),
        filename_(arena),
        md5_(arena),
        fileuuid_(arena),
        imageurl198_(arena),
        imageurl720_(arena),
        originimageurl_(arena),
        picpath_(arena) {}

inline void Element::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, elementid_),
           0,
           offsetof(Impl_, unknown_47422_) -
               offsetof(Impl_, elementid_) +
               sizeof(Impl_::unknown_47422_));
}
Element::~Element() {
  // @@protoc_insertion_point(destructor:nt_msg.Element)
  SharedDtor(*this);
}
inline void Element::SharedDtor(MessageLite& self) {
  Element& this_ = static_cast<Element&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.senderuidstr_.Destroy();
  this_._impl_.textstr_.Destroy();
  this_._impl_.filename_.Destroy();
  this_._impl_.md5_.Destroy();
  this_._impl_.fileuuid_.Destroy();
  this_._impl_.imageurl198_.Destroy();
  this_._impl_.imageurl720_.Destroy();
  this_._impl_.originimageurl_.Destroy();
  this_._impl_.picpath_.Destroy();
  this_._impl_.~Impl_();
}

inline void* Element::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Element(arena);
}
constexpr auto Element::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Element, _impl_.sourcemsgtextelems_) +
          decltype(Element::_impl_.sourcemsgtextelems_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(Element), alignof(Element), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Element::PlacementNew_,
                                 sizeof(Element),
                                 alignof(Element));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Element::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Element_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Element::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Element>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Element::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Element>(), &Element::ByteSizeLong,
            &Element::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Element, _impl_._cached_size_),
        false,
    },
    &Element::kDescriptorMethods,
    &descriptor_table_message_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Element::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 30, 1, 125, 48> Element::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Element, _impl_._has_bits_),
    0, // no _extensions_
    47423, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_entries),
    30,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nt_msg::Element>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    40020, 0, 1,
    65534, 0,45001, 0, 1,
     65532, 1,45101, 0, 1,
     65532, 3,45402, 0, 7,
     41446, 5, 65534, 13, 65535, 14,
    65535, 14, 65535, 14, 65535, 14, 65503, 14,45802, 0, 2,
     64448, 15, 63487, 22,
    47402, 0, 2,
    48632, 23, 65487, 28,
    65535, 65535
  }}, {{
    // optional string senderUidStr = 40020;
    {PROTOBUF_FIELD_OFFSET(Element, _impl_.senderuidstr_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int64 elementId = 45001;
    {PROTOBUF_FIELD_OFFSET(Element, _impl_.elementid_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // int32 elementType = 45002;
    {PROTOBUF_FIELD_OFFSET(Element, _impl_.elementtype_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // optional string textStr = 45101;
    {PROTOBUF_FIELD_OFFSET(Element, _impl_.textstr_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional int32 atType = 45102;
    {PROTOBUF_FIELD_OFFSET(Element, _impl_.attype_), _Internal::kHasBitsOffset + 9, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional string fileName = 45402;
    {PROTOBUF_FIELD_OFFSET(Element, _impl_.filename_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional int32 fileSize = 45405;
    {PROTOBUF_FIELD_OFFSET(Element, _impl_.filesize_), _Internal::kHasBitsOffset + 10, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional bytes md5 = 45406;
    {PROTOBUF_FIELD_OFFSET(Element, _impl_.md5_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional int32 picWidth = 45411;
    {PROTOBUF_FIELD_OFFSET(Element, _impl_.picwidth_), _Internal::kHasBitsOffset + 11, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 picHeight = 45412;
    {PROTOBUF_FIELD_OFFSET(Element, _impl_.picheight_), _Internal::kHasBitsOffset + 12, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 unknown_45413 = 45413;
    {PROTOBUF_FIELD_OFFSET(Element, _impl_.unknown_45413_), _Internal::kHasBitsOffset + 13, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 unknown_45414 = 45414;
    {PROTOBUF_FIELD_OFFSET(Element, _impl_.unknown_45414_), _Internal::kHasBitsOffset + 14, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 picType = 45416;
    {PROTOBUF_FIELD_OFFSET(Element, _impl_.pictype_), _Internal::kHasBitsOffset + 15, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 unknown_45418 = 45418;
    {PROTOBUF_FIELD_OFFSET(Element, _impl_.unknown_45418_), _Internal::kHasBitsOffset + 16, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional string fileUuid = 45503;
    {PROTOBUF_FIELD_OFFSET(Element, _impl_.fileuuid_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string imageUrl198 = 45802;
    {PROTOBUF_FIELD_OFFSET(Element, _impl_.imageurl198_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string imageUrl720 = 45803;
    {PROTOBUF_FIELD_OFFSET(Element, _impl_.imageurl720_), _Internal::kHasBitsOffset + 6, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional string originImageUrl = 45804;
    {PROTOBUF_FIELD_OFFSET(Element, _impl_.originimageurl_), _Internal::kHasBitsOffset + 7, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional int32 unknown_45805 = 45805;
    {PROTOBUF_FIELD_OFFSET(Element, _impl_.unknown_45805_), _Internal::kHasBitsOffset + 17, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int64 unknown_45806 = 45806;
    {PROTOBUF_FIELD_OFFSET(Element, _impl_.unknown_45806_), _Internal::kHasBitsOffset + 18, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional int32 unknown_45807 = 45807;
    {PROTOBUF_FIELD_OFFSET(Element, _impl_.unknown_45807_), _Internal::kHasBitsOffset + 19, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional string picPath = 45812;
    {PROTOBUF_FIELD_OFFSET(Element, _impl_.picpath_), _Internal::kHasBitsOffset + 8, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional int32 unknown_45829 = 45829;
    {PROTOBUF_FIELD_OFFSET(Element, _impl_.unknown_45829_), _Internal::kHasBitsOffset + 20, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 replayMsgSeq = 47402;
    {PROTOBUF_FIELD_OFFSET(Element, _impl_.replaymsgseq_), _Internal::kHasBitsOffset + 21, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 senderUid = 47403;
    {PROTOBUF_FIELD_OFFSET(Element, _impl_.senderuid_), _Internal::kHasBitsOffset + 22, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 replyMsgTime = 47404;
    {PROTOBUF_FIELD_OFFSET(Element, _impl_.replymsgtime_), _Internal::kHasBitsOffset + 23, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 unknown_47411 = 47411;
    {PROTOBUF_FIELD_OFFSET(Element, _impl_.unknown_47411_), _Internal::kHasBitsOffset + 24, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int64 unknown_47416 = 47416;
    {PROTOBUF_FIELD_OFFSET(Element, _impl_.unknown_47416_), _Internal::kHasBitsOffset + 25, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // optional int64 unknown_47422 = 47422;
    {PROTOBUF_FIELD_OFFSET(Element, _impl_.unknown_47422_), _Internal::kHasBitsOffset + 26, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // repeated .nt_msg.Element.SourceMsgTextElem sourceMsgTextElems = 47423;
    {PROTOBUF_FIELD_OFFSET(Element, _impl_.sourcemsgtextelems_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::nt_msg::Element_SourceMsgTextElem>()},
  }}, {{
    "\16\14\0\0\7\0\10\0\0\0\0\0\0\0\0\10\13\13\16\0\0\0\7\0\0\0\0\0\0\0\0\0"
    "nt_msg.Element"
    "senderUidStr"
    "textStr"
    "fileName"
    "fileUuid"
    "imageUrl198"
    "imageUrl720"
    "originImageUrl"
    "picPath"
  }},
};

PROTOBUF_NOINLINE void Element::Clear() {
// @@protoc_insertion_point(message_clear_start:nt_msg.Element)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.sourcemsgtextelems_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.senderuidstr_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.textstr_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.filename_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000008u) {
      _impl_.md5_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000010u) {
      _impl_.fileuuid_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000020u) {
      _impl_.imageurl198_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000040u) {
      _impl_.imageurl720_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000080u) {
      _impl_.originimageurl_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x00000100u) {
    _impl_.picpath_.ClearNonDefaultToEmpty();
  }
  ::memset(&_impl_.elementid_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.elementtype_) -
      reinterpret_cast<char*>(&_impl_.elementid_)) + sizeof(_impl_.elementtype_));
  if (cached_has_bits & 0x0000fe00u) {
    ::memset(&_impl_.attype_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.pictype_) -
        reinterpret_cast<char*>(&_impl_.attype_)) + sizeof(_impl_.pictype_));
  }
  if (cached_has_bits & 0x00ff0000u) {
    ::memset(&_impl_.unknown_45418_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.replymsgtime_) -
        reinterpret_cast<char*>(&_impl_.unknown_45418_)) + sizeof(_impl_.replymsgtime_));
  }
  if (cached_has_bits & 0x07000000u) {
    ::memset(&_impl_.unknown_47411_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.unknown_47422_) -
        reinterpret_cast<char*>(&_impl_.unknown_47411_)) + sizeof(_impl_.unknown_47422_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Element::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Element& this_ = static_cast<const Element&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Element::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Element& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:nt_msg.Element)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional string senderUidStr = 40020;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_senderuidstr();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nt_msg.Element.senderUidStr");
            target = stream->WriteStringMaybeAliased(40020, _s, target);
          }

          // int64 elementId = 45001;
          if (this_._internal_elementid() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteInt64ToArray(
                45001, this_._internal_elementid(), target);
          }

          // int32 elementType = 45002;
          if (this_._internal_elementtype() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteInt32ToArray(
                45002, this_._internal_elementtype(), target);
          }

          // optional string textStr = 45101;
          if (cached_has_bits & 0x00000002u) {
            const std::string& _s = this_._internal_textstr();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nt_msg.Element.textStr");
            target = stream->WriteStringMaybeAliased(45101, _s, target);
          }

          // optional int32 atType = 45102;
          if (cached_has_bits & 0x00000200u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteInt32ToArray(
                45102, this_._internal_attype(), target);
          }

          // optional string fileName = 45402;
          if (cached_has_bits & 0x00000004u) {
            const std::string& _s = this_._internal_filename();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nt_msg.Element.fileName");
            target = stream->WriteStringMaybeAliased(45402, _s, target);
          }

          // optional int32 fileSize = 45405;
          if (cached_has_bits & 0x00000400u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteInt32ToArray(
                45405, this_._internal_filesize(), target);
          }

          // optional bytes md5 = 45406;
          if (cached_has_bits & 0x00000008u) {
            const std::string& _s = this_._internal_md5();
            target = stream->WriteBytesMaybeAliased(45406, _s, target);
          }

          // optional int32 picWidth = 45411;
          if (cached_has_bits & 0x00000800u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteInt32ToArray(
                45411, this_._internal_picwidth(), target);
          }

          // optional int32 picHeight = 45412;
          if (cached_has_bits & 0x00001000u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteInt32ToArray(
                45412, this_._internal_picheight(), target);
          }

          // optional int32 unknown_45413 = 45413;
          if (cached_has_bits & 0x00002000u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteInt32ToArray(
                45413, this_._internal_unknown_45413(), target);
          }

          // optional int32 unknown_45414 = 45414;
          if (cached_has_bits & 0x00004000u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteInt32ToArray(
                45414, this_._internal_unknown_45414(), target);
          }

          // optional int32 picType = 45416;
          if (cached_has_bits & 0x00008000u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteInt32ToArray(
                45416, this_._internal_pictype(), target);
          }

          // optional int32 unknown_45418 = 45418;
          if (cached_has_bits & 0x00010000u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteInt32ToArray(
                45418, this_._internal_unknown_45418(), target);
          }

          // optional string fileUuid = 45503;
          if (cached_has_bits & 0x00000010u) {
            const std::string& _s = this_._internal_fileuuid();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nt_msg.Element.fileUuid");
            target = stream->WriteStringMaybeAliased(45503, _s, target);
          }

          // optional string imageUrl198 = 45802;
          if (cached_has_bits & 0x00000020u) {
            const std::string& _s = this_._internal_imageurl198();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nt_msg.Element.imageUrl198");
            target = stream->WriteStringMaybeAliased(45802, _s, target);
          }

          // optional string imageUrl720 = 45803;
          if (cached_has_bits & 0x00000040u) {
            const std::string& _s = this_._internal_imageurl720();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nt_msg.Element.imageUrl720");
            target = stream->WriteStringMaybeAliased(45803, _s, target);
          }

          // optional string originImageUrl = 45804;
          if (cached_has_bits & 0x00000080u) {
            const std::string& _s = this_._internal_originimageurl();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nt_msg.Element.originImageUrl");
            target = stream->WriteStringMaybeAliased(45804, _s, target);
          }

          // optional int32 unknown_45805 = 45805;
          if (cached_has_bits & 0x00020000u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteInt32ToArray(
                45805, this_._internal_unknown_45805(), target);
          }

          // optional int64 unknown_45806 = 45806;
          if (cached_has_bits & 0x00040000u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteInt64ToArray(
                45806, this_._internal_unknown_45806(), target);
          }

          // optional int32 unknown_45807 = 45807;
          if (cached_has_bits & 0x00080000u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteInt32ToArray(
                45807, this_._internal_unknown_45807(), target);
          }

          // optional string picPath = 45812;
          if (cached_has_bits & 0x00000100u) {
            const std::string& _s = this_._internal_picpath();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nt_msg.Element.picPath");
            target = stream->WriteStringMaybeAliased(45812, _s, target);
          }

          // optional int32 unknown_45829 = 45829;
          if (cached_has_bits & 0x00100000u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteInt32ToArray(
                45829, this_._internal_unknown_45829(), target);
          }

          // optional int32 replayMsgSeq = 47402;
          if (cached_has_bits & 0x00200000u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteInt32ToArray(
                47402, this_._internal_replaymsgseq(), target);
          }

          // optional int32 senderUid = 47403;
          if (cached_has_bits & 0x00400000u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteInt32ToArray(
                47403, this_._internal_senderuid(), target);
          }

          // optional int32 replyMsgTime = 47404;
          if (cached_has_bits & 0x00800000u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteInt32ToArray(
                47404, this_._internal_replymsgtime(), target);
          }

          // optional int32 unknown_47411 = 47411;
          if (cached_has_bits & 0x01000000u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteInt32ToArray(
                47411, this_._internal_unknown_47411(), target);
          }

          // optional int64 unknown_47416 = 47416;
          if (cached_has_bits & 0x02000000u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteInt64ToArray(
                47416, this_._internal_unknown_47416(), target);
          }

          // optional int64 unknown_47422 = 47422;
          if (cached_has_bits & 0x04000000u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteInt64ToArray(
                47422, this_._internal_unknown_47422(), target);
          }

          // repeated .nt_msg.Element.SourceMsgTextElem sourceMsgTextElems = 47423;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_sourcemsgtextelems_size());
               i < n; i++) {
            const auto& repfield = this_._internal_sourcemsgtextelems().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    47423, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:nt_msg.Element)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Element::ByteSizeLong(const MessageLite& base) {
          const Element& this_ = static_cast<const Element&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Element::ByteSizeLong() const {
          const Element& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:nt_msg.Element)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .nt_msg.Element.SourceMsgTextElem sourceMsgTextElems = 47423;
            {
              total_size += 3UL * this_._internal_sourcemsgtextelems_size();
              for (const auto& msg : this_._internal_sourcemsgtextelems()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x000000ffu) {
            // optional string senderUidStr = 40020;
            if (cached_has_bits & 0x00000001u) {
              total_size += 3 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_senderuidstr());
            }
            // optional string textStr = 45101;
            if (cached_has_bits & 0x00000002u) {
              total_size += 3 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_textstr());
            }
            // optional string fileName = 45402;
            if (cached_has_bits & 0x00000004u) {
              total_size += 3 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_filename());
            }
            // optional bytes md5 = 45406;
            if (cached_has_bits & 0x00000008u) {
              total_size += 3 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_md5());
            }
            // optional string fileUuid = 45503;
            if (cached_has_bits & 0x00000010u) {
              total_size += 3 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_fileuuid());
            }
            // optional string imageUrl198 = 45802;
            if (cached_has_bits & 0x00000020u) {
              total_size += 3 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_imageurl198());
            }
            // optional string imageUrl720 = 45803;
            if (cached_has_bits & 0x00000040u) {
              total_size += 3 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_imageurl720());
            }
            // optional string originImageUrl = 45804;
            if (cached_has_bits & 0x00000080u) {
              total_size += 3 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_originimageurl());
            }
          }
           {
            // optional string picPath = 45812;
            if (cached_has_bits & 0x00000100u) {
              total_size += 3 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_picpath());
            }
          }
           {
            // int64 elementId = 45001;
            if (this_._internal_elementid() != 0) {
              total_size += 3 + ::_pbi::WireFormatLite::Int64Size(
                                              this_._internal_elementid());
            }
            // int32 elementType = 45002;
            if (this_._internal_elementtype() != 0) {
              total_size += 3 + ::_pbi::WireFormatLite::Int32Size(
                                              this_._internal_elementtype());
            }
          }
          if (cached_has_bits & 0x0000fe00u) {
            // optional int32 atType = 45102;
            if (cached_has_bits & 0x00000200u) {
              total_size += 3 + ::_pbi::WireFormatLite::Int32Size(
                                              this_._internal_attype());
            }
            // optional int32 fileSize = 45405;
            if (cached_has_bits & 0x00000400u) {
              total_size += 3 + ::_pbi::WireFormatLite::Int32Size(
                                              this_._internal_filesize());
            }
            // optional int32 picWidth = 45411;
            if (cached_has_bits & 0x00000800u) {
              total_size += 3 + ::_pbi::WireFormatLite::Int32Size(
                                              this_._internal_picwidth());
            }
            // optional int32 picHeight = 45412;
            if (cached_has_bits & 0x00001000u) {
              total_size += 3 + ::_pbi::WireFormatLite::Int32Size(
                                              this_._internal_picheight());
            }
            // optional int32 unknown_45413 = 45413;
            if (cached_has_bits & 0x00002000u) {
              total_size += 3 + ::_pbi::WireFormatLite::Int32Size(
                                              this_._internal_unknown_45413());
            }
            // optional int32 unknown_45414 = 45414;
            if (cached_has_bits & 0x00004000u) {
              total_size += 3 + ::_pbi::WireFormatLite::Int32Size(
                                              this_._internal_unknown_45414());
            }
            // optional int32 picType = 45416;
            if (cached_has_bits & 0x00008000u) {
              total_size += 3 + ::_pbi::WireFormatLite::Int32Size(
                                              this_._internal_pictype());
            }
          }
          if (cached_has_bits & 0x00ff0000u) {
            // optional int32 unknown_45418 = 45418;
            if (cached_has_bits & 0x00010000u) {
              total_size += 3 + ::_pbi::WireFormatLite::Int32Size(
                                              this_._internal_unknown_45418());
            }
            // optional int32 unknown_45805 = 45805;
            if (cached_has_bits & 0x00020000u) {
              total_size += 3 + ::_pbi::WireFormatLite::Int32Size(
                                              this_._internal_unknown_45805());
            }
            // optional int64 unknown_45806 = 45806;
            if (cached_has_bits & 0x00040000u) {
              total_size += 3 + ::_pbi::WireFormatLite::Int64Size(
                                              this_._internal_unknown_45806());
            }
            // optional int32 unknown_45807 = 45807;
            if (cached_has_bits & 0x00080000u) {
              total_size += 3 + ::_pbi::WireFormatLite::Int32Size(
                                              this_._internal_unknown_45807());
            }
            // optional int32 unknown_45829 = 45829;
            if (cached_has_bits & 0x00100000u) {
              total_size += 3 + ::_pbi::WireFormatLite::Int32Size(
                                              this_._internal_unknown_45829());
            }
            // optional int32 replayMsgSeq = 47402;
            if (cached_has_bits & 0x00200000u) {
              total_size += 3 + ::_pbi::WireFormatLite::Int32Size(
                                              this_._internal_replaymsgseq());
            }
            // optional int32 senderUid = 47403;
            if (cached_has_bits & 0x00400000u) {
              total_size += 3 + ::_pbi::WireFormatLite::Int32Size(
                                              this_._internal_senderuid());
            }
            // optional int32 replyMsgTime = 47404;
            if (cached_has_bits & 0x00800000u) {
              total_size += 3 + ::_pbi::WireFormatLite::Int32Size(
                                              this_._internal_replymsgtime());
            }
          }
          if (cached_has_bits & 0x07000000u) {
            // optional int32 unknown_47411 = 47411;
            if (cached_has_bits & 0x01000000u) {
              total_size += 3 + ::_pbi::WireFormatLite::Int32Size(
                                              this_._internal_unknown_47411());
            }
            // optional int64 unknown_47416 = 47416;
            if (cached_has_bits & 0x02000000u) {
              total_size += 3 + ::_pbi::WireFormatLite::Int64Size(
                                              this_._internal_unknown_47416());
            }
            // optional int64 unknown_47422 = 47422;
            if (cached_has_bits & 0x04000000u) {
              total_size += 3 + ::_pbi::WireFormatLite::Int64Size(
                                              this_._internal_unknown_47422());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Element::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Element*>(&to_msg);
  auto& from = static_cast<const Element&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:nt_msg.Element)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_sourcemsgtextelems()->MergeFrom(
      from._internal_sourcemsgtextelems());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_senderuidstr(from._internal_senderuidstr());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_textstr(from._internal_textstr());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_filename(from._internal_filename());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_internal_set_md5(from._internal_md5());
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_internal_set_fileuuid(from._internal_fileuuid());
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_internal_set_imageurl198(from._internal_imageurl198());
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_internal_set_imageurl720(from._internal_imageurl720());
    }
    if (cached_has_bits & 0x00000080u) {
      _this->_internal_set_originimageurl(from._internal_originimageurl());
    }
  }
  if (cached_has_bits & 0x00000100u) {
    _this->_internal_set_picpath(from._internal_picpath());
  }
  if (from._internal_elementid() != 0) {
    _this->_impl_.elementid_ = from._impl_.elementid_;
  }
  if (from._internal_elementtype() != 0) {
    _this->_impl_.elementtype_ = from._impl_.elementtype_;
  }
  if (cached_has_bits & 0x0000fe00u) {
    if (cached_has_bits & 0x00000200u) {
      _this->_impl_.attype_ = from._impl_.attype_;
    }
    if (cached_has_bits & 0x00000400u) {
      _this->_impl_.filesize_ = from._impl_.filesize_;
    }
    if (cached_has_bits & 0x00000800u) {
      _this->_impl_.picwidth_ = from._impl_.picwidth_;
    }
    if (cached_has_bits & 0x00001000u) {
      _this->_impl_.picheight_ = from._impl_.picheight_;
    }
    if (cached_has_bits & 0x00002000u) {
      _this->_impl_.unknown_45413_ = from._impl_.unknown_45413_;
    }
    if (cached_has_bits & 0x00004000u) {
      _this->_impl_.unknown_45414_ = from._impl_.unknown_45414_;
    }
    if (cached_has_bits & 0x00008000u) {
      _this->_impl_.pictype_ = from._impl_.pictype_;
    }
  }
  if (cached_has_bits & 0x00ff0000u) {
    if (cached_has_bits & 0x00010000u) {
      _this->_impl_.unknown_45418_ = from._impl_.unknown_45418_;
    }
    if (cached_has_bits & 0x00020000u) {
      _this->_impl_.unknown_45805_ = from._impl_.unknown_45805_;
    }
    if (cached_has_bits & 0x00040000u) {
      _this->_impl_.unknown_45806_ = from._impl_.unknown_45806_;
    }
    if (cached_has_bits & 0x00080000u) {
      _this->_impl_.unknown_45807_ = from._impl_.unknown_45807_;
    }
    if (cached_has_bits & 0x00100000u) {
      _this->_impl_.unknown_45829_ = from._impl_.unknown_45829_;
    }
    if (cached_has_bits & 0x00200000u) {
      _this->_impl_.replaymsgseq_ = from._impl_.replaymsgseq_;
    }
    if (cached_has_bits & 0x00400000u) {
      _this->_impl_.senderuid_ = from._impl_.senderuid_;
    }
    if (cached_has_bits & 0x00800000u) {
      _this->_impl_.replymsgtime_ = from._impl_.replymsgtime_;
    }
  }
  if (cached_has_bits & 0x07000000u) {
    if (cached_has_bits & 0x01000000u) {
      _this->_impl_.unknown_47411_ = from._impl_.unknown_47411_;
    }
    if (cached_has_bits & 0x02000000u) {
      _this->_impl_.unknown_47416_ = from._impl_.unknown_47416_;
    }
    if (cached_has_bits & 0x04000000u) {
      _this->_impl_.unknown_47422_ = from._impl_.unknown_47422_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Element::CopyFrom(const Element& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nt_msg.Element)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Element::InternalSwap(Element* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.sourcemsgtextelems_.InternalSwap(&other->_impl_.sourcemsgtextelems_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.senderuidstr_, &other->_impl_.senderuidstr_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.textstr_, &other->_impl_.textstr_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.filename_, &other->_impl_.filename_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.md5_, &other->_impl_.md5_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.fileuuid_, &other->_impl_.fileuuid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.imageurl198_, &other->_impl_.imageurl198_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.imageurl720_, &other->_impl_.imageurl720_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.originimageurl_, &other->_impl_.originimageurl_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.picpath_, &other->_impl_.picpath_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Element, _impl_.unknown_47422_)
      + sizeof(Element::_impl_.unknown_47422_)
      - PROTOBUF_FIELD_OFFSET(Element, _impl_.elementid_)>(
          reinterpret_cast<char*>(&_impl_.elementid_),
          reinterpret_cast<char*>(&other->_impl_.elementid_));
}

::google::protobuf::Metadata Element::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Elements::_Internal {
 public:
};

Elements::Elements(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:nt_msg.Elements)
}
inline PROTOBUF_NDEBUG_INLINE Elements::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::nt_msg::Elements& from_msg)
      : elem_{visibility, arena, from.elem_},
        _cached_size_{0} {}

Elements::Elements(
    ::google::protobuf::Arena* arena,
    const Elements& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Elements* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:nt_msg.Elements)
}
inline PROTOBUF_NDEBUG_INLINE Elements::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : elem_{visibility, arena},
        _cached_size_{0} {}

inline void Elements::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Elements::~Elements() {
  // @@protoc_insertion_point(destructor:nt_msg.Elements)
  SharedDtor(*this);
}
inline void Elements::SharedDtor(MessageLite& self) {
  Elements& this_ = static_cast<Elements&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* Elements::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Elements(arena);
}
constexpr auto Elements::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Elements, _impl_.elem_) +
          decltype(Elements::_impl_.elem_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(Elements), alignof(Elements), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Elements::PlacementNew_,
                                 sizeof(Elements),
                                 alignof(Elements));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Elements::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Elements_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Elements::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Elements>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Elements::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Elements>(), &Elements::ByteSizeLong,
            &Elements::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Elements, _impl_._cached_size_),
        false,
    },
    &Elements::kDescriptorMethods,
    &descriptor_table_message_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Elements::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 7> Elements::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    40800, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nt_msg::Elements>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    40800, 0, 1,
    65534, 0,
    65535, 65535
  }}, {{
    // repeated .nt_msg.Element elem = 40800;
    {PROTOBUF_FIELD_OFFSET(Elements, _impl_.elem_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::nt_msg::Element>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void Elements::Clear() {
// @@protoc_insertion_point(message_clear_start:nt_msg.Elements)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.elem_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Elements::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Elements& this_ = static_cast<const Elements&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Elements::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Elements& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:nt_msg.Elements)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .nt_msg.Element elem = 40800;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_elem_size());
               i < n; i++) {
            const auto& repfield = this_._internal_elem().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    40800, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:nt_msg.Elements)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Elements::ByteSizeLong(const MessageLite& base) {
          const Elements& this_ = static_cast<const Elements&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Elements::ByteSizeLong() const {
          const Elements& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:nt_msg.Elements)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .nt_msg.Element elem = 40800;
            {
              total_size += 3UL * this_._internal_elem_size();
              for (const auto& msg : this_._internal_elem()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Elements::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Elements*>(&to_msg);
  auto& from = static_cast<const Elements&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:nt_msg.Elements)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_elem()->MergeFrom(
      from._internal_elem());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Elements::CopyFrom(const Elements& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:nt_msg.Elements)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Elements::InternalSwap(Elements* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.elem_.InternalSwap(&other->_impl_.elem_);
}

::google::protobuf::Metadata Elements::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace nt_msg
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_message_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
